version: '3.8'
services:
  vibraniumdome-app:
    container_name: vibraniumdome-app
    image: vibraniumdome/vibraniumdome-app:0.1.0
    ports:
      - "3000:3000"
    env_file:
      - ./vibraniumdome-app/.env.example
    environment:
      - DATABASE_URL=mysql://root:@vibraniumdome-app-db:3306/vibraniumdome
    depends_on:
      - vibraniumdome-app-db

  vibraniumdome-app-db:
    container_name: vibraniumdome-app-db
    image: mysql:8.1.0
    volumes:
      - ./vibraniumdome-app/vibraniumdome-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: vibranium
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
  
  vibraniumdome-shields:
    container_name: vibraniumdome-shields
    image: vibraniumdome/vibraniumdome-shields:0.1.0
    ports:
      - "5001:5001"
    env_file:
      - ./vibraniumdome-shields/.env.example
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - /tmp:/tmp
    depends_on:
      - vibraniumdome-app

  vibraniumdome-opensearch-node-1:
    image: opensearchproject/opensearch:2.9.0
    container_name: vibraniumdome-opensearch-node-1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=vibraniumdome-opensearch-node-1
      - discovery.seed_hosts=vibraniumdome-opensearch-node-1,vibraniumdome-opensearch-node-2
      - cluster.initial_cluster_manager_nodes=vibraniumdome-opensearch-node-1,vibraniumdome-opensearch-node-2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - ./vibraniumdome-opensearch/vibraniumdome-opensearch-data1:/usr/share/opensearch/data
      - ./vibraniumdome-opensearch/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
      - ./vibraniumdome-opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch-security/opensearch.yml
      - ./vibraniumdome-opensearch/log4j2.properties:/usr/share/opensearch/config/log4j2.properties
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer

  vibraniumdome-opensearch-node-2:
    image: opensearchproject/opensearch:2.9.0
    container_name: vibraniumdome-opensearch-node-2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=vibraniumdome-opensearch-node-2
      - discovery.seed_hosts=vibraniumdome-opensearch-node-1,vibraniumdome-opensearch-node-2
      - cluster.initial_cluster_manager_nodes=vibraniumdome-opensearch-node-1,vibraniumdome-opensearch-node-2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./vibraniumdome-opensearch/vibraniumdome-opensearch-data2:/usr/share/opensearch/data
      - ./vibraniumdome-opensearch/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
      - ./vibraniumdome-opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch-security/opensearch.yml
      - ./vibraniumdome-opensearch/log4j2.properties:/usr/share/opensearch/config/log4j2.properties

  vibraniumdome-opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: vibraniumdome-opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://vibraniumdome-opensearch-node-1:9200","https://vibraniumdome-opensearch-node-2:9200"]'
    volumes:
      - ./vibraniumdome-opensearch/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
  
  vibraniumdome-opensearch-seeder:
    image: centos
    container_name: vibraniumdome-opensearch-seeder
    volumes:
      - ./vibraniumdome-opensearch/dashboard.ndjson:/dashboard.ndjson
      - ./vibraniumdome-opensearch/opensearch-seed.sh:/opensearch-seed.sh
    command: /bin/bash /opensearch-seed.sh
    depends_on:
      - vibraniumdome-opensearch-node-1
      - vibraniumdome-opensearch-node-2
      - vibraniumdome-opensearch-dashboards

volumes:
  vibraniumdome-opensearch-data1:
  vibraniumdome-opensearch-data2:
  vibraniumdome-db-data: